token: TokenTimeIsBackBuddyss           

engines:
  standard:                               # Engine used for standard chess and when no suitable special engine is configured.
    dir: "./engines"                      # Directory containing the engine.
    name: "stockfish-ubuntu-x86-64-bmi2"                     # Binary name of the engine to use.
    ponder: true                          # Think on opponent's time.
    silence_stderr: false                 # Suppresses stderr output.
    move_overhead_multiplier: 23.0         # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    uci_options:                          # Arbitrary UCI options passed to the engine.
      Threads: 7                          # Max CPU threads the engine can use.
      Hash: 5500                           # Max memory (in megabytes) the engine can allocate.
      Move Overhead: 100                  # Increase if your bot flags games too often.
    limits:
    
  variants:                               
    dir: "./engines"                     
    name: "fairy-sf"             
    ponder: true                       
    silence_stderr: false               
    move_overhead_multiplier: 1.0        
    uci_options:                      
      Threads: 6                         
      Hash: 4096                         
      Move Overhead: 100            
      Use NNUE: true
      EvalFile: "3check-cb5f517c228b.nnue:antichess-dd3cbe53cd4e.nnue:atomic-2cf13ff256cc.nnue:crazyhouse-8ebf84784ad2.nnue:horde-28173ddccabe.nnue:kingofthehill-978b86d0e6a4.nnue:racingkings-636b95f085e3.nnue"
    limits:

  chess960:                             
    dir: "./engines"                     
    name: "chess960sf"                    
    ponder: true                          # Think on opponent's time.
    silence_stderr: false                 # Suppresses stderr output.
    move_overhead_multiplier: 10.0         # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    uci_options:                          # Arbitrary UCI options passed to the engine. (Commenting allowed)
      Threads: 6                          # Max CPU threads the engine can use.
      Hash: 2048                           # Max memory (in megabytes) the engine can allocate.
      Move Overhead: 200                  # Increase if your bot flags games too often. 
      UCI_Chess960: true 
    limits:                               # Limits that end the move calculation early.
      time: 3.0                           # Max time per move in seconds. 
    
syzygy:
  standard:
    enabled: false                       
    paths:                             
      - "./engines/syzygy"
    max_pieces: 7                     
    instant_play: true                
  antichess:
    enabled: false                     
    paths:                        
      - "/path/to/antichess/syzygy"
    max_pieces: 6                        
    instant_play: true                   
  atomic:
    enabled: false                     
    paths:                             
      - "/path/to/atomic/syzygy"
    max_pieces: 6                      
    instant_play: true               

gaviota:
  enabled: false                  
  paths:                             
    - "/path/to/gaviota"
  max_pieces: 5                     

opening_books:
  enabled: true         
  priority: 400       
  books:
    bullet:
      selection: best_move   
      names:
        - probook
    standard_white:
      selection: best_move
      names:
        - probook
    standard_black:
      selection: best_move
      names:
        - probook
    standard:
      selection: best_move
      names:
        - probook
online_moves:
  opening_explorer:
    enabled: false                        # Activate online moves from Lichess opening explorer. The move that has performed best for this bot is played.
    priority: 300                         # Priority with which this move source is used. Higher priority is used first.
#   player: Username                      # Player whose Lichess opening explorer should be used. Comment this to use your own or with anti your opponent's.
    only_without_book: false              # Whether the Lichess opening explorer should only be used if there is no matching book.
    use_for_variants: false               # Whether the Lichess opening explorer should be used for other variants than standard and chess960.
    min_time: 10                          # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 5                            # Time the server has to respond.
    min_games: 5                          # Minimum number of games in which the position must have occurred.
    only_with_wins: false                 # Whether to play only moves that have won before.
    selection: "performance"              # Move selection is "performance" or "win_rate".
    anti: false                           # Whether to play the moves in which the opponent performs the worst.
#   max_depth: 16                         # Half move max depth. (Comment this line for max depth)
#   max_moves: 1                          # Max number of moves played from Lichess opening explorer. (Comment this line for max moves)
  lichess_cloud:
    enabled: false                        # Activate online moves from Lichess cloud eval.
    priority: 200                         # Priority with which this move source is used. Higher priority is used first.
    only_without_book: false              # Whether the cloud should only be used if there is no matching book.
    use_for_variants: false               # Whether the cloud should be used for other variants than standard and chess960.
    min_eval_depth: 10                    # Minimum evaluation depth.
    min_time: 10                          # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 5                            # Time the server has to respond.
#   max_depth: 16                         # Half move max depth. (Comment this line for max depth)
#   max_moves: 1                          # Max number of moves played from Lichess cloud eval. (Comment this line for max moves)
  chessdb:
    enabled: true                        # Activate online moves from https://chessdb.cn/queryc_en/
    priority: 100                         # Priority with which this move source is used. Higher priority is used first.
    only_without_book: false              # Whether the chessdb should only be used if there is no matching book.
    min_candidates: 1                     # Minimum number of candidate moves.
    min_time: 10                          # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 5                            # Time the server has to respond.
    selection: "best"                     # Move selection is one of "optimal", "best" or "good".
#   max_depth: 16                         # Half move max depth. (Comment this line for max depth)
#   max_moves: 1                          # Max number of moves played from chessdb. (Comment this line for max moves)
  online_egtb:
    enabled: true                        # Activate online endgame tablebases from Lichess.
    min_time: 20                           # Time the bot must have at least to use the online move. +10 seconds in games without increment.
    timeout: 3                            # Time the server has to respond.

offer_draw:
  enabled: true                           # Activate whether the bot should offer draw.
  score: 10                               # If the absolute value of the score is less than or equal to this value, the bot offers/accepts draw (in cp)
  consecutive_moves: 10                   # How many moves in a row the absolute value of the score has to be below the draw value
  min_game_length: 35                     # Earliest move in which draw is offered.
  against_humans: true                    # Activate whether these settings should apply against humans.
# min_rating: 2300                        # Minimum rating of opponent to offer draw.

resign:
  enabled: false                          # Activate whether the bot should resign games.
  score: -1000                            # If the score is less than or equal to this value, the bot resigns (in cp).
  consecutive_moves: 5                    # How many moves in a row the score has to be below the resign value.
  against_humans: true                    # Activate whether these settings should apply against humans.
# min_rating: 2300                        # Minimum rating of opponent to resign.

challenge:                                # Incoming challenges.
  concurrency: 1                          # Number of games to play simultaneously.
  max_takebacks: 3                        # Maximum number of takebacks granted to a human.
  bullet_with_increment_only: false       # Whether bullet games against BOTs should only be accepted with increment.
# min_increment: 0                        # Minimum amount of increment to accept a challenge.
# max_increment: 180                      # Maximum amount of increment to accept a challenge.
# min_initial: 0                          # Minimum amount of initial time to accept a challenge.
# max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants:                               # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
#   - fromPosition
    - antichess
    - atomic
    - crazyhouse
    - horde
    - kingOfTheHill
    - racingKings
    - threeCheck
  time_controls:                          # Speeds or time controls in initial_minutes+increment_seconds format to accept.
    - bullet
    - blitz
#    - rapid
#   - classical
#   - 25+0
  bot_modes:                              # Game modes to accept against BOTs.
    - casual                              # Unrated games.
    - rated                               # Rated games
  human_modes:                            # Game modes to accept against humans.
    - casual                              # Unrated games.
#    - rated                               # Rated games
    
matchmaking:
  delay: 60                               
  timeout: 30                           
  selection: cyclic                  
  types:
    bullet:
      tc: 0.5+0
      rated: true
      variant: standard

    chess960:
      tc: 0.5+0
      rated: true
      variant: chess960
    
  # Time control in initial_minutes+increment_seconds format.
#   casual_chess960:
#     tc: 0.5+1
#     rated: false
#     variant: chess960
#   optional_settings:
#     rated: true                   
#     variant: standard                 
#     weight: 100                     
#     multiplier: 15                   
#    min_rating_diff: 100              
#    max_rating_diff: 1000              

messages:
  # Optional substitution keywords (include curly braces):
  #   {opponent} to insert the opponent's name
  #   {me} to insert our name
  #   {engine} to insert engine name
  #   {cpu} to insert CPU information
  #   {ram} to insert RAM size
  # Any other words in curly braces will be removed.
  greeting: "Hey, I'm running {engine}. Good luck! Type !help for a list of commands."  
  goodbye: "Good game, see you next time."                                             
  greeting_spectators: "Hey, I'm running {engine}. Type !help for a list of commands." 
  goodbye_spectators: "Thanks for watching."                                           
    
whitelist:                                # List of users whose challenges are always accepted.
# - Username1
# - Username2

blacklist:                                # List of users who are not challenged and whose challenges are declined.
# - Username1
# - Username2

books:                                  
  Titans: "engines/Titans.bin"
  probook: "./engines/probook.bin"
